language: php
php:
  - 7.2

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - mysql -e 'create database phinx_test;'
  - cd $TRAVIS_BUILD_DIR

script:
  - ant check-style
  - ant phpstan
  - ant phpunit-coverage

