language: php
php:
  - 7.2
  - 7.3

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - mysql -e 'create database phinx_test;'
  - cd $TRAVIS_BUILD_DIR

script:
  - ant check-style
  - ant phpstan
  - ant phpunit-coverage

after_success:
#  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
#  - if [ "$TRAVIS_PHP_VERSION" == "7.2" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
